config/routes.rb
Cartify::Engine.routes.draw do
  resource :cart, only: %i[show update]
  resources :order_items, only: %i[create update destroy]
  resources :orders, only: %i[index show]
  resources :checkout

  match 'settings/addresses', to: 'addresses#index', via: 'get'
  match 'settings/addresses', to: 'addresses#create', via: 'post'
end

app/models/cartify/address.rb
module Cartify
  class Address < ApplicationRecord
    belongs_to :user, class_name: Cartify.user_class.to_s, optional: true
    belongs_to :order, optional: true

    scope :shipping, -> { where(type: 'Cartify::Shipping') }
    scope :billing, -> { where(type: 'Cartify::Billing') }

    validates :first_name, :last_name, :address, :city, :zip, :country, :phone, presence: true
    validates_length_of :first_name, :last_name, :address, :city, :country, maximum: 49
    validates :first_name, :last_name, format: { with: /\A[A-Za-z]{0,49}\z/ }
    validates :city, :country, format: { with: /\A[A-Za-z\s]{0,49}\z/ }
    validates :address, format: { with: /\A[-A-Za-z\s\d,]{0,49}\z/ }

    validates_length_of :phone, maximum: 15
    validates_length_of :zip, maximum: 10
    before_validation :clear_mask

    def clear_mask
      phone&.gsub!(/[-\s()]/, '')
    end
  end
end

app/models/cartify/application_record.rb
module Cartify
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/cartify/billing.rb
module Cartify
  class Billing < Address
  end
end

app/models/cartify/coupon.rb
module Cartify
  class Coupon < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :value, presence: true
    validates :value, numericality: { only_float: true }
    validates_length_of :name, is: 15

    has_many :orders
  end
end

app/models/cartify/credit_card.rb
module Cartify
  class CreditCard < ApplicationRecord
    validates :number, :name, :mm_yy, :cvv, presence: true
    validates_length_of :cvv, in: 3..4
    validates :cvv, numericality: { only_integer: true }
    validates_format_of :mm_yy, with: %r{\A(0[1-9]|10|11|12)\/\d\d\z}, message: I18n.t('validation.mm_yy')
    validates_format_of :number, with: /\A\d{16}\z/, message: I18n.t('validation.cart_number')
    validates_format_of :name, with: /\A[a-zA-Z\s]{0,49}\z/, message: I18n.t('validation.cart_name')
    before_validation :clear_mask
    has_one :order

    after_save :connect_to_order

    private

    def connect_to_order
      user = CurrentSession.user unless CurrentSession.user.nil?
      user&.orders&.where_status(:in_progress)&.first&.update_attributes(credit_card_id: id)
    end

    def clear_mask
      number&.gsub!(/\s/, '')
    end
  end
end

app/models/cartify/delivery.rb
module Cartify
  class Delivery < ApplicationRecord
    has_many :orders
    validates :name, :duration, :price, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }
    validates_length_of :name, in: 3..100
  end
end

app/models/cartify/order.rb
module Cartify
  class Order < ApplicationRecord
    belongs_to :order_status
    belongs_to :coupon, optional: true
    belongs_to :user, class_name: Cartify.user_class.to_s, optional: true
    belongs_to :delivery, optional: true
    belongs_to :credit_card, optional: true
    has_many :order_items, dependent: :destroy
    has_many :addresses, dependent: :destroy
    has_one :billing
    has_one :shipping
    has_many :products, class_name: Cartify.product_class.to_s, through: :order_items
    before_validation :set_order_status, on: :create
    before_save :update_subtotal, :update_total, :connect_to_user

    scope :where_status, ->(status_name) { joins(:order_status).where(cartify_order_statuses: { name: status_name }) }
    scope :processing_list, -> { joins(:order_status).where(cartify_order_statuses: { name: %i[in_queue in_progress in_delivery] }) }
    scope :processing_order, -> { where_status('in_queue').order('updated_at').last }
    scope :in_progress, -> { where_status('in_progress').first.try(:id) }

    def subtotal
      order_items.sum(&:total_price)
    end

    def total
      subtotal_item_total + shipping_price
    end

    def subtotal_item_total
      subtotal - discount
    end

    def discount
      coupon.try(:value) || 0.00
    end

    def shipping_price
      delivery.try(:price) || 0.00
    end

    def finalize
      set_order_status :in_queue
      save!
    end

    private

    def set_order_status(status = :in_progress)
      self.order_status_id = Cartify::OrderStatus.find_or_create_by(name: status).id
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end

    def update_total
      self[:total] = total
    end

    def connect_to_user
      self[:user_id] = CurrentSession.user.id unless CurrentSession.user.nil?
    end
  end
end

app/models/cartify/order_item.rb
module Cartify
  class OrderItem < ApplicationRecord
    belongs_to :product, class_name: Cartify.product_class.to_s
    belongs_to :order
    has_one :order_status, through: :order
    has_one :category, through: :product, class_name: Cartify.product_class.to_s

    validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validate :product_present
    validate :order_present

    before_save :finalize
    default_scope { order(product_id: :asc) }

    def unit_price
      return self[:unit_price] if persisted?
      product.send(Cartify.price_attribute)
    end

    def total_price
      unit_price * quantity
    end

    private

    def product_present
      errors.add(:product, 'is not valid or is not active.') if product.nil?
    end

    def order_present
      errors.add(:order, 'is not a valid order.') if order.nil?
    end

    def finalize
      self[:unit_price] = unit_price
      self[:total_price] = quantity * self[:unit_price]
    end
  end
end

app/models/cartify/order_status.rb
module Cartify
  class OrderStatus < ApplicationRecord
    has_many :orders

    validates :name, presence: true, uniqueness: true
    validates_length_of :name, maximum: 30

    scope :prohibited_to_change, -> { where(name: %i[in_progress in_queue]) }

    def valid_step?(target)
      if Cartify::OrderStatus.find(target).name == 'delivered'
        name == 'in_delivery'
      else
        Cartify::OrderStatus.prohibited_to_change.ids.exclude? target.to_i
      end
    end
  end
end

app/models/cartify/shipping.rb
module Cartify
  class Shipping < Address
  end
end

app/controllers/cartify/addresses_controller.rb
module Cartify
  class AddressesController < Cartify::ApplicationController
    def index
      @addresses = Cartify::AddressesForm.new(user_id: cartify_current_user.id)
    end

    def create
      @addresses = Cartify::AddressesForm.new(addresses_params)
      render :index, object: @addresses.errors
    end

    private

    def addresses_params
      params.require(:addresses_form)
    end
  end
end

app/controllers/cartify/application_controller.rb
module Cartify
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
    include Cartify::Authenticatable
  end
end

app/controllers/cartify/carts_controller.rb
require_dependency 'cartify/application_controller'

module Cartify
  class CartsController < Cartify::ApplicationController
    def show
      @order_items = current_order.order_items
    end

    def update
      current_order.update_attributes(coupon_id: coupon.id) if coupon
      redirect_to cart_path, notice: coupon ? t('flash.coupon_applied') : t('flash.fake_coupon')
    end

    private

    def coupon
      @coupon ||= Cartify::Coupon.find_by(name: params[:name])
    end
  end
end

app/controllers/cartify/checkout_controller.rb
require_dependency 'cartify/application_controller'

module Cartify
  class CheckoutController < Cartify::ApplicationController
    before_action :fast_authentification!
    include Wicked::Wizard
    include Showable
    include Updatable

    steps :login, :addresses, :delivery, :payment, :confirm, :complete

    def show
      return redirect_to main_app.public_send(Cartify.empty_cart_path) if no_items_in_cart?
      send("show_#{step}") unless step == 'wicked_finish'
      render_wizard
    end

    def update
      send("update_#{step}")
      redirect_to next_wizard_path unless performed?
    end

    private

    def no_items_in_cart?
      current_order.order_items.empty? && step != :complete
    end
  end
end

app/controllers/cartify/order_items_controller.rb
require_dependency 'cartify/application_controller'

module Cartify
  class OrderItemsController < Cartify::ApplicationController
    def create
      current_order.save
      @order_item = current_order.order_items.find_or_initialize_by(product_id: order_item_params[:product_id])
      session[:order_id] = current_order.id if update_quantity.save
    end

    def update
      @order_item = current_order.order_items.find(params[:id])
      @order_item.update_attributes(order_item_params)
      @order_items = current_order.order_items
    end

    def destroy
      @order_item = current_order.order_items.find(params[:id])
      @order_item.destroy
      @order_items = current_order.order_items
    end

    private

    def order_item_params
      params.require(:order_item).permit(:quantity, :product_id)
    end

    def update_quantity
      qqty = order_item_params[:quantity].to_i
      @order_item.quantity = qqty + @order_item.quantity.to_i
      @order_item
    end
  end
end

app/controllers/cartify/orders_controller.rb
require_dependency 'cartify/application_controller'

module Cartify
  class OrdersController < Cartify::ApplicationController
    before_action :cartify_authenticate_user!

    def index
      all_in_one = cartify_current_user.orders.includes(:delivery, :order_status, :order_items)
      @orders = Cartify::OrdersQuery.new(all_in_one).run(params[:filter]).decorate
    end

    def show
      @order = cartify_current_user.orders.find(params[:id]).decorate
      redirect_to checkout_path(:confirm) if @order.status == t('order.status.in_progress')
    end
  end
end

app/helpers/cartify/application_helper.rb
module Cartify
  module ApplicationHelper
    def shop_icon_quantity
      qty = current_order.order_items.reload.collect(&:quantity).compact.sum
      if qty.zero?
        "<span class='shop-quantity' id='order-details'>You have not added any dishes yet!</span>".html_safe
      else
        "<span class='shop-quantity' id='order-details'>#{pluralize(qty, 'item')}</span>".html_safe
      end 
    end

    def active_class(link_path)
      return '' if request.GET.empty?
      link_path.include? request.GET.first.join('=') ? 'active' : ''
    end

    def country_name(object)
      country = ISO3166::Country[object.country]
      country.translations[I18n.locale.to_s] || country.name
    end

    def image_for(obj)
      begin
          obj.product_image 
      rescue => exception
          'https://vignette.wikia.nocookie.net/teenage-mutant-ninja-turtles-2012-series/images/f/fd/Pizza_trad_pepperoni.png/revision/latest?cb=20161106191944'
      end
    end
  end
end

app/helpers/cartify/carts_helper.rb
module Cartify
  module CartsHelper
    def add_to_cart(product, qqty = 1, name = 'Add to cart')
      link_to name,
              cartify.order_items_path(order_item: { quantity: qqty, product_id: product&.id }),
              method: :post,
              remote: true
    end
  end
end

app/helpers/cartify/checkout_helper.rb
module Cartify
  module CheckoutHelper
    def active_step?(current_step)
      'active' if current_step == step
    end

    def order_summary_text_position
      return 'text-center general-text-right' if right?
      'general-text-align'
    end

    def order_summary_table_position
      'general-summary-table-right general-text-right' if right?
    end

    private

    def right?
      %i[confirm complete].include? step
    end
  end
end

app/helpers/cartify/order_helper.rb
module Cartify::OrderHelper
  def order_active_filter
    case request.GET[:filter]
    when 'in_progress' then t('order.status.in_progress')
    when 'in_queue' then t('order.status.in_queue')
    when 'in_delivery' then t('order.status.in_delivery')
    when 'delivered' then t('order.status.delivered')
    when 'canceled' then t('order.status.canceled')
    else t('order.status.all')
    end
  end
end

app/views/cartify/shared/_address.haml
.form-group{ class: "#{errors.messages[:first_name].empty? ? '' : 'has-error'}" }
  = ff.label :first_name, t('settings.first_name'), class: 'control-label input-label'
  = ff.text_field :first_name, class: 'form-control',  autocomplete: 'off', placeholder: t('settings.first_name')
  %span.help-block= errors.messages[:first_name].to_sentence
.form-group{ class: "#{errors.messages[:last_name].empty? ? '' : 'has-error'}" }
  = ff.label :last_name, class: 'control-label input-label'
  = ff.text_field :last_name, class: 'form-control',  autocomplete: 'off', placeholder: t('settings.last_name')
  %span.help-block= errors.messages[:last_name].to_sentence
.form-group{ class: "#{errors.messages[:address].empty? ? '' : 'has-error'}" }
  = ff.label :address, t('settings.address'), class: 'control-label input-label'
  = ff.text_field :address, class: 'form-control',  autocomplete: 'off', placeholder: t('settings.address')
  %span.help-block= errors.messages[:address].to_sentence
.form-group{ class: "#{errors.messages[:city].empty? ? '' : 'has-error'}" }
  = ff.label :city, t('settings.city'), class: 'control-label input-label'
  = ff.text_field :city, class: 'form-control',  autocomplete: 'off', placeholder: t('settings.city')
  %span.help-block= errors.messages[:city].to_sentence
.form-group{ class: "#{errors.messages[:zip].empty? ? '' : 'has-error'}" }
  = ff.label :zip, t('settings.zip'), class: 'control-label input-label'
  = ff.text_field :zip, class: 'form-control',  autocomplete: 'off', placeholder: t('settings.zip')
  %span.help-block= errors.messages[:zip].to_sentence
.form-group{ class: "#{errors.messages[:country].empty? ? '' : 'has-error'}" }
  = ff.label :country, t('settings.country'), class: 'control-label input-label'
  = ff.country_select(:country, { priority_countries: ['UA'], placeholder: t('settings.country_select') }, { class: 'form-control', id: 'country' } )
  %span.help-block= errors.messages[:country].to_sentence 
.form-group.mb-55{ class: "#{errors.messages[:phone].empty? ? '' : 'has-error'}" }
  = ff.label :phone, 'Phone', class: 'control-label input-label'
  = ff.text_field :phone, class: 'form-control',  autocomplete: 'off', placeholder: 'Example +355 66 123 4567'
  %span.help-block= errors.messages[:phone].to_sentence

app/views/cartify/shared/_addresses_form.haml
#addres.general-main-wrap.tab-pane.fade.in.active{role: "tabpanel"}
  = form_for @addresses, url: settings_addresses_path do |f|
    .hidden-xs.hidden-sm
      .row
        .col-md-5
          %h3.general-subtitle.mt-0= t('settings.billing')
        .col-md-5.col-md-offset-1
          %h3.general-subtitle.mt-0= t('settings.shipping')
    .row
      .col-md-5.mb-40
        .visible-xs.visible-sm
          %h3.general-subtitle.mt-0= t('settings.billing')
        = f.fields_for @addresses.billing do |ff|
          - bill_errors = @addresses.billing.errors
          = render 'cartify/shared/address', ff: ff, errors: bill_errors
          = f.hidden_field "[billing][user_id]", value: cartify_current_user.id
      .col-md-5.col-md-offset-1.mb-25
        .visible-xs.visible-sm
          %h3.general-subtitle.mt-0= t('settings.shipping')
        = f.fields_for @addresses.shipping do |ff|
          - ship_errors = @addresses.shipping.errors
          = render 'cartify/shared/address', ff: ff, errors: ship_errors
          = f.hidden_field "[shipping][user_id]", value: cartify_current_user.id
        .form-group.checkbox
          %label.checkbox-label
            = f.check_box :use_billing, class: 'checkbox-input', id: 'use_billing', hidden: true
            %span.checkbox-icon
              %i.fa.fa-check
            %span.checkbox-text= t('settings.use_billing')
    .ral-text-align.mb-60
      = f.submit t('settings.save'), class: 'button btn btn-default center-block mb-20'

app/views/cartify/shared/_checkout_summary_numbers.haml
%tr
  %td
    %p.font-16= t('confirm.item_total')+':'
  %td
    %p.font-16= number_to_currency current_order.subtotal_item_total
%tr
  %td
    %p.font-16= t('confirm.shipping')+':' unless step == :address
  %td
    %p.font-16= number_to_currency current_order.shipping_price unless step == :address
%tr
  %td
    %strong.font-16= t('cart.total')+':'
  %td
    %strong.font-16= number_to_currency current_order.total || '--'

app/views/cartify/shared/_order_summary_numbers.haml
%tr
  %td
    %p.font-16= t('cart.subtotal')+':'
  %td
    %p.font-16= number_to_currency current_order.subtotal
%tr
  %td
    %p.font-16= t('cart.coupon')+':'
  %td
    %p.font-16= number_to_currency current_order.discount
%tr
  %td
    %strong.font-16= t('cart.total')+':'
  %td
    %strong.font-16= number_to_currency current_order.total || '--'